# Generated by Django 5.1 on 2025-12-31 17:27

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, help_text="Product image", null=True, upload_to="products/"
            ),
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variation_type",
                    models.CharField(
                        choices=[
                            ("color", "Color"),
                            ("size", "Size"),
                            ("material", "Material"),
                            ("style", "Style"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Red, Large, Cotton, etc.", max_length=50
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Optional: hex color code, dimensions, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0, help_text="Quantity available for this variation"
                    ),
                ),
                (
                    "price_adjustment",
                    models.FloatField(
                        default=0.0,
                        help_text="Price adjustment for this variation (+/-)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this variation is currently available",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="store.item",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Variations",
                "ordering": ["variation_type", "name"],
                "unique_together": {("item", "variation_type", "name")},
            },
        ),
    ]
