# Generated by Django 5.1 on 2026-01-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_logistics_alter_company_options"),
        ("store", "0002_item_image_productvariation"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="logistics",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the logistics company for this delivery",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.logistics",
                verbose_name="Logistics Company",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                help_text="Package tracking number",
                max_length=100,
                null=True,
                verbose_name="Tracking Number",
            ),
        ),
    ]
