# Generated by Django 5.1 on 2026-01-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_delivery_logistics_delivery_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter phone number (e.g., +977 98XXXXXXXX or 01-XXXXXXX)",
                max_length=30,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
    ]
