# Generated by Django 5.1 on 2026-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_delivery_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="cost_price",
            field=models.FloatField(
                default=0.0,
                help_text="Cost price of the product (purchase price)",
                verbose_name="Cost Price",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="low_stock_threshold",
            field=models.IntegerField(
                default=10,
                help_text="Alert when stock falls below this quantity",
                verbose_name="Low Stock Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(
                default=0,
                help_text="Price at which the product is sold to customers",
                verbose_name="Selling Price",
            ),
        ),
    ]
