# Generated by Django 5.1 on 2026-06-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_stock_adjustment_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Stock keeping unit / product code', max_length=64, verbose_name='SKU'),
        ),
    ]
