# Generated by Django 5.1 on 2026-05-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_bill_amount'),
        ('transactions', '0009_rename_delivery_fields_to_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='linked_inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_bill_documents', to='transactions.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='bill',
            name='linked_purchase',
            field=models.ForeignKey(blank=True, help_text='Canonical purchase in transactions app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_bills', to='transactions.purchase'),
        ),
    ]
