# Generated by Django 5.1 on 2026-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_purchase_lines_receipt_gate_payments_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number of the institution', max_length=30, null=True),
        ),
    ]
