# Generated by Django 5.1 on 2026-01-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="SB Vision", max_length=100, verbose_name="Company Name"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="Tom Mboya Street, Tudor",
                        max_length=255,
                        null=True,
                        verbose_name="Street Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="+2547 00 000000",
                        max_length=30,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "po_box",
                    models.CharField(
                        blank=True,
                        default="P.O BOX. 90420-80100 MSA",
                        max_length=100,
                        null=True,
                        verbose_name="P.O Box",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Website"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Information",
                "verbose_name_plural": "Company Information",
            },
        ),
    ]
