# Generated by Django 5.1 on 2026-01-10 15:37

import django_extensions.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Logistics Company Name"
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contact Person",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(
                        blank=True,
                        help_text="URL template for tracking (use {tracking_number} as placeholder)",
                        max_length=500,
                        null=True,
                        verbose_name="Tracking URL Template",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this logistics company is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Logistics Company",
                "verbose_name_plural": "Logistics Companies",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["id"],
                "verbose_name": "Company",
                "verbose_name_plural": "Company Information",
            },
        ),
    ]
