# Generated by Django 5.1 on 2026-06-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vendor_payables_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount the customer owed before system records (debit balance).', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount owed to this supplier before system records.', max_digits=12),
        ),
    ]
