# Generated by Django 5.1 on 2026-06-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contact_ledger_and_sale_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receivables_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual +/- adjustment on customer balance (+ owes more, − credit).', max_digits=12),
        ),
    ]
