# Generated by Django 5.1 on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_vendor_vat_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter phone number (e.g., +977 98XXXXXXXX or 01-XXXXXXX)",
                max_length=30,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
    ]
