# Generated by Django 5.1 on 2026-06-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_vendor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance_date',
            field=models.DateTimeField(blank=True, help_text='As-of date for the customer opening balance.', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_balance_date',
            field=models.DateTimeField(blank=True, help_text='As-of date for the supplier opening balance.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN / tax ID (optional)', max_length=20, null=True, verbose_name='PAN number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN / tax ID (optional)', max_length=20, null=True, verbose_name='PAN number'),
        ),
    ]
