# Generated by Django 5.1 on 2026-05-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_inventorytransaction_inventorytransactionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='inventory_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_purchase', to='transactions.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='sale',
            name='inventory_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_sale', to='transactions.inventorytransaction'),
        ),
    ]
