# Generated by Django 5.1 on 2026-05-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_purchase_inventory_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vat_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
