# Generated by Django 5.1 on 2026-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_purchase_amount_paid_purchase_amount_remaining_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="source_ref",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("U", "Unpaid"),
                    ("T", "Partial"),
                    ("D", "Paid"),
                    ("X", "Overpaid"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["item", "created_at"], name="stock_movem_item_id_4b5ee0_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventorytransactionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="inv_txn_item_quantity_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransactionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="inv_txn_item_unit_price_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransactionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_total__gte", 0)),
                name="inv_txn_item_line_total_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stock_move_quantity_gt_zero",
            ),
        ),
    ]
