# Generated by Django 5.1 on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_purchase_payment_status_inventorytransaction_source_ref_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="delivery_date",
            new_name="receipt_date",
        ),
        migrations.RenameField(
            model_name="purchase",
            old_name="delivery_status",
            new_name="receipt_status",
        ),
    ]
