# Generated by Django 5.1 on 2026-05-09 14:32

import django.db.models.deletion
from django.db import migrations, models


def backfill_purchase_lines(apps, schema_editor):
    Purchase = apps.get_model("transactions", "Purchase")
    PurchaseLine = apps.get_model("transactions", "PurchaseLine")
    for p in Purchase.objects.iterator():
        if PurchaseLine.objects.filter(purchase_id=p.pk).exists():
            continue
        if p.item_id and (p.quantity or 0) > 0:
            PurchaseLine.objects.create(
                purchase_id=p.pk,
                item_id=p.item_id,
                quantity=int(p.quantity or 0),
                unit_price=p.price or 0,
                line_total=0,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_item_cost_price_item_low_stock_threshold_and_more'),
        ('transactions', '0009_rename_delivery_fields_to_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='stock_movem_item_id_bbae3b_idx',
            old_name='stock_movem_item_id_4b5ee0_idx',
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('payment', 'Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Deprecated: use Purchase lines.', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='receipt_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Receipt Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='receipt_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Received')], default='P', max_length=1, verbose_name='Receipt Status'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='inventory_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payment', to='transactions.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='transactions.sale'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.item'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.purchase'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='inventory_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payment', to='transactions.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to='transactions.purchase'),
        ),
        migrations.RunPython(backfill_purchase_lines, noop_reverse),
    ]
