# Generated by Django 5.1 on 2026-06-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_saledetail_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-order_date', '-id']},
        ),
    ]
