# Generated by Django 5.1 on 2026-06-05 09:48

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Sum


def backfill_sale_payment_fields(apps, schema_editor):
    Sale = apps.get_model("transactions", "Sale")
    CustomerPayment = apps.get_model("transactions", "CustomerPayment")
    for sale in Sale.objects.all().iterator():
        paid = Decimal(str(sale.amount_paid or 0))
        if CustomerPayment.objects.filter(sale_id=sale.pk).exists():
            agg = CustomerPayment.objects.filter(sale_id=sale.pk).aggregate(s=Sum("amount"))
            paid = Decimal(str(agg["s"] or 0))
        grand = Decimal(str(sale.grand_total or 0))
        remaining = grand - paid
        if paid == 0:
            status = "U"
        elif remaining > 0:
            status = "T"
        elif remaining == 0:
            status = "D"
        else:
            status = "X"
        Sale.objects.filter(pk=sale.pk).update(
            amount_remaining=remaining,
            payment_status=status,
            amount_change=paid - grand,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_sale_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('U', 'Unpaid'), ('T', 'Partial'), ('D', 'Paid'), ('X', 'Overpaid')], default='U', max_length=1),
        ),
        migrations.RunPython(backfill_sale_payment_fields, migrations.RunPython.noop),
    ]
