# Generated by Django 5.1 on 2026-06-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_contact_ledger_and_sale_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_account_payment_only',
            field=models.BooleanField(default=False, help_text='Payment-only account entry; hide the bill row in supplier ledger.'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_account_receipt_only',
            field=models.BooleanField(default=False, help_text='Payment-only account entry; hide the sale row in customer ledger.'),
        ),
    ]
