# Generated by Django 5.1 on 2026-05-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_grand_total_and_more'),
        ('transactions', '0009_rename_delivery_fields_to_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='linked_inventory_transaction',
            field=models.ForeignKey(blank=True, help_text='Optional link to unified inventory/accounting txn.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_invoice_documents', to='transactions.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='linked_sale',
            field=models.ForeignKey(blank=True, help_text='Canonical sale in transactions app (recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_invoices', to='transactions.sale'),
        ),
    ]
